name: Tests

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: make

    - name: Test
      shell: bash
      run: make tests
      
  Windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: pwsh
      run: make

    - name: Test
      shell: pwsh
      run: make tests
